name: xylophone
description: Sixth Flutter app from App Brewery Flutter course.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  audioplayers: 0.15.1

flutter:
  uses-material-design: true
  assets:
    - assets/
